### ISSUE TITLE
axes don't match plot 

### ISSUE THREAD

**Issue by gmonaie** [jumpingrivers/prettyB#13]
```
dat <- matrix(c(0:19, rnorm(20)), ncol = 2)

plot(dat)
plot_p(dat)
```
plot correctly sizes the axes range, but plot_p creates y axis range of up to 20, and a x axes range of up to 40

plot_p is not functioning as a drop-in replacement in this case

**Comment by csgillespie** [comment]
I suspect there's a plot.matrix command going on here. 

I'll to look fix it soon.
